"""remove content column from jobpostings

Revision ID: 03bef9348adc
Revises: 2375bef0eaaa
Create Date: 2025-11-13 12:49:36.605272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bef9348adc'
down_revision: Union[str, None] = '2375bef0eaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpostings', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('content', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
