"""update calumns in resume

Revision ID: 0749d43af066
Revises: b9b0ada8a6c5
Create Date: 2025-11-10 16:54:07.862475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0749d43af066'
down_revision: Union[str, None] = 'b9b0ada8a6c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('gender', sa.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'gender')
    # ### end Alembic commands ###
