"""add description in Activity

Revision ID: 16a31b03b8a8
Revises: 93f6e44c57dd
Create Date: 2025-11-10 12:03:04.492699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a31b03b8a8'
down_revision: Union[str, None] = '93f6e44c57dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('description', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'description')
    # ### end Alembic commands ###
