"""add memo

Revision ID: 18f2a926d54c
Revises: 00c2eb73eb59
Create Date: 2025-11-07 11:58:38.897427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f2a926d54c'
down_revision: Union[str, None] = '00c2eb73eb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('memo', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpostings', 'memo')
    # ### end Alembic commands ###
