"""expand varchar column sizes for resume content

Revision ID: 2375bef0eaaa
Revises: c8f1e9d2a3b4
Create Date: 2025-11-13 00:37:03.766660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2375bef0eaaa'
down_revision: Union[str, None] = 'c8f1e9d2a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('educations', 'organ',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('educations', 'department',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('educations', 'degree_level',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('educations', 'score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('experiences', 'job_title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('experiences', 'department',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('experiences', 'position',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('qualifications', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('qualifications', 'score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('qualifications', 'organ',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('technologystacks', 'title',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technologystacks', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('qualifications', 'organ',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('qualifications', 'score',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('qualifications', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('experiences', 'position',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('experiences', 'department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('experiences', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('educations', 'score',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('educations', 'degree_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('educations', 'department',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('educations', 'organ',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('activities', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
