"""init

Revision ID: 26f9681d0325
Revises: 
Create Date: 2025-11-05 15:04:08.985090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f9681d0325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('division', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('code_id', 'detail_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.VARCHAR(length=22), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_sanctions', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('jobpostings',
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('title', sa.VARCHAR(length=30), nullable=False),
    sa.Column('company', sa.VARCHAR(length=30), nullable=False),
    sa.Column('content', sa.VARCHAR(length=300), nullable=True),
    sa.Column('qualification', sa.VARCHAR(length=300), nullable=False),
    sa.Column('prefer', sa.VARCHAR(length=300), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('posting_id')
    )
    op.create_table('useractiviylogs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('userblacklists',
    sa.Column('blacklist_id', sa.Integer(), nullable=False),
    sa.Column('blocked_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.Column('blocked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('block_period', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blacklist_id')
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=30), nullable=False),
    sa.Column('resume_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('military_service', sa.VARCHAR(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('self_introduction', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['jobpostings.posting_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('studyguides',
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['jobpostings.posting_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guide_id')
    )
    op.create_table('activities',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('educations',
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('organ', sa.VARCHAR(length=20), nullable=False),
    sa.Column('department', sa.VARCHAR(length=20), nullable=False),
    sa.Column('degree_level', sa.VARCHAR(length=10), nullable=True),
    sa.Column('score', sa.VARCHAR(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('education_id')
    )
    op.create_table('experiences',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('department', sa.VARCHAR(length=20), nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), nullable=True),
    sa.Column('job_description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('employment_status', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id')
    )
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('fileable_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.VARCHAR(length=10), nullable=False),
    sa.Column('fileable_table', sa.VARCHAR(length=30), nullable=False),
    sa.Column('org_file_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('mod_file_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_rul', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fileable_id'], ['resumes.resume_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('interviews',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['jobpostings.posting_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('qualifications',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('score', sa.VARCHAR(length=10), nullable=True),
    sa.Column('organ', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_table('resumefeedbacks',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('parent_content', sa.Text(), nullable=False),
    sa.Column('matching_rate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['jobpostings.posting_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('studyitems',
    sa.Column('study_item_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.VARCHAR(length=200), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['guide_id'], ['studyguides.guide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_item_id')
    )
    op.create_table('technologystacks',
    sa.Column('technology_stack_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('technology_stack_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=300), nullable=False),
    sa.Column('answer', sa.VARCHAR(length=300), nullable=False),
    sa.Column('feedback', sa.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('feedbackcontents',
    sa.Column('feedbackcontent_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('feedback_devision', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feedback_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['resumefeedbacks.feedback_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedbackcontent_id')
    )
    op.create_table('interviewfeedbacks',
    sa.Column('interview_feedback_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=5), nullable=False),
    sa.Column('content', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_feedback_id')
    )
    op.create_table('studykeywords',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('study_item_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['study_item_id'], ['studyitems.study_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studykeywords')
    op.drop_table('interviewfeedbacks')
    op.drop_table('feedbackcontents')
    op.drop_table('conversations')
    op.drop_table('technologystacks')
    op.drop_table('studyitems')
    op.drop_table('resumefeedbacks')
    op.drop_table('qualifications')
    op.drop_table('projects')
    op.drop_table('interviews')
    op.drop_table('files')
    op.drop_table('experiences')
    op.drop_table('educations')
    op.drop_table('activities')
    op.drop_table('studyguides')
    op.drop_table('resumes')
    op.drop_table('userblacklists')
    op.drop_table('useractiviylogs')
    op.drop_table('jobpostings')
    op.drop_table('users')
    op.drop_table('codes')
    # ### end Alembic commands ###
