"""expand resume title from varchar(30) to varchar(100)

Revision ID: 2e3231736bcc
Revises: 72361d77de7e
Create Date: 2025-11-18 21:10:51.046171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3231736bcc'
down_revision: Union[str, None] = '72361d77de7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
