"""rename is_activate to is_active

Revision ID: 9691ce0c30b0
Revises: f5682a838810
Create Date: 2025-11-17 07:36:19.269343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9691ce0c30b0'
down_revision: Union[str, None] = 'f5682a838810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('jobpostings', 'is_activate')
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('resumes', 'is_activate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'is_active')
    op.add_column('jobpostings', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('jobpostings', 'is_active')
    # ### end Alembic commands ###
