"""rename is_activate to is_active in users and interview_feedbacks

Revision ID: 974b0b6876b3
Revises: 9691ce0c30b0
Create Date: 2025-11-17 11:59:50.190467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974b0b6876b3'
down_revision: Union[str, None] = '9691ce0c30b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get the database connection to check current state
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Handle users table
    if 'users' in inspector.get_table_names():
        columns = {col['name'] for col in inspector.get_columns('users')}
        # If is_activate exists and is_active doesn't, rename it
        if 'is_activate' in columns and 'is_active' not in columns:
            op.drop_column('users', 'is_activate')
            op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
        # If both exist, just drop is_activate
        elif 'is_activate' in columns and 'is_active' in columns:
            op.drop_column('users', 'is_activate')
        # If only is_active exists, do nothing (already renamed)

    # Handle studyguides table
    if 'studyguides' in inspector.get_table_names():
        columns = {col['name'] for col in inspector.get_columns('studyguides')}
        # If is_activate exists and is_active doesn't, rename it
        if 'is_activate' in columns and 'is_active' not in columns:
            op.drop_column('studyguides', 'is_activate')
            op.add_column('studyguides', sa.Column('is_active', sa.Boolean(), nullable=True))
        # If both exist, just drop is_activate
        elif 'is_activate' in columns and 'is_active' in columns:
            op.drop_column('studyguides', 'is_activate')
        # If only is_active exists, do nothing (already renamed)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.add_column('studyguides', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('studyguides', 'is_active')
    # ### end Alembic commands ###
