"""rename is_activate to is_active in users and interview_feedbacks

Revision ID: 974b0b6876b3
Revises: 9691ce0c30b0
Create Date: 2025-11-17 11:59:50.190467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974b0b6876b3'
down_revision: Union[str, None] = '9691ce0c30b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studyguides', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('studyguides', 'is_activate')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_activate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.add_column('studyguides', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('studyguides', 'is_active')
    # ### end Alembic commands ###
