"""add updated_at to jobpostings

Revision ID: 98458def8511
Revises: 03bef9348adc
Create Date: 2025-11-13 16:26:16.026189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98458def8511'
down_revision: Union[str, None] = '03bef9348adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpostings', 'updated_at')
    # ### end Alembic commands ###
