"""update file table

Revision ID: b4102b2dc46a
Revises: f71746117f84
Create Date: 2025-11-11 06:33:49.079399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4102b2dc46a'
down_revision: Union[str, None] = 'f71746117f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_key', sa.VARCHAR(length=100), nullable=False))
    op.add_column('files', sa.Column('purpose', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('files', 'file_rul')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_rul', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('files', 'purpose')
    op.drop_column('files', 'file_key')
    # ### end Alembic commands ###
