"""update column type to varchar -Code(detail_id)

Revision ID: b5a294d40dd5
Revises: 0749d43af066
Create Date: 2025-11-10 18:54:20.380770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a294d40dd5'
down_revision: Union[str, None] = '0749d43af066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codes', 'detail_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codes', 'detail_id',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
