"""add soft delete in jobposting

Revision ID: b9b0ada8a6c5
Revises: 16a31b03b8a8
Create Date: 2025-11-10 15:53:07.316804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b0ada8a6c5'
down_revision: Union[str, None] = '16a31b03b8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.add_column('resumes', sa.Column('name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'name')
    op.drop_column('jobpostings', 'is_activate')
    # ### end Alembic commands ###
