"""populate updated_at with created_at for jobpostings

Revision ID: c0e3e7a4d2b6
Revises: 98458def8511
Create Date: 2025-11-13 17:13:34.467708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e3e7a4d2b6'
down_revision: Union[str, None] = '98458def8511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 jobpostings 데이터의 updated_at을 created_at으로 채우기
    op.execute(
        "UPDATE jobpostings SET updated_at = created_at WHERE updated_at IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # downgrade는 복구할 수 없으므로 pass 처리
    pass
    # ### end Alembic commands ###
