"""add end_date column to jobpostings

Revision ID: c8f1e9d2a3b4
Revises: b4102b2dc46a
Create Date: 2025-11-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f1e9d2a3b4'
down_revision: Union[str, None] = 'b4102b2dc46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobpostings', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpostings', 'end_date')
    # ### end Alembic commands ###
