"""add military_service column to users

Revision ID: de7648f8f197
Revises: ce8c0424aba4
Create Date: 2025-11-14 11:46:08.034516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7648f8f197'
down_revision: Union[str, None] = 'ce8c0424aba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('military_service', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###

    # Populate military_service with default values based on gender
    # Male (gender='1') -> military_service='2' (군필)
    # Female (gender='2') -> military_service='6' (해당없음)
    op.execute(
        "UPDATE users SET military_service = '2' WHERE gender = '1'"
    )
    op.execute(
        "UPDATE users SET military_service = '6' WHERE gender = '2'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'military_service')
    # ### end Alembic commands ###
