"""remove memo column from jobpostings

Revision ID: f5682a838810
Revises: c003fbf3a339
Create Date: 2025-11-16 02:57:05.974867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5682a838810'
down_revision: Union[str, None] = 'c003fbf3a339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobpostings', 'memo')
    op.add_column('resumes', sa.Column('is_activate', sa.Boolean(), nullable=True))
    op.drop_column('resumes', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'is_activate')
    op.add_column('jobpostings', sa.Column('memo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
